-- Go into pdb
ALTER SESSION SET CONTAINER=ORCLPDB1;

-- create user
CREATE USER FASIH IDENTIFIED BY FASIHTEST;
ALTER USER FASIH QUOTA UNLIMITED ON USERS;

-- grant login
GRANT CREATE SESSION TO FASIH;

--grant create table
GRANT CREATE TABLE TO FASIH;
