version: '3.9'
services:
  kibana:
    image: kibana:${STACK_VERSION}
    container_name: kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'

volumes:
  kibanadata:
    driver: local

networks:
  default:
    name: k_cluster_net
    external: true