version: "3.2"

services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: 'oracle19c'
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_SID = ORCLCDB 
      - ORACLE_PDB = ORCLPDB 
      - ORACLE_PWD = poc123
    volumes:
      - ./data:/opt/oracle/oradata
      - ./scripts:/home/oracle/scripts

networks:
  default:
    name: k_cluster_net
    external: true