ALTER SESSION SET CONTAINER=CDB$ROOT;
SELECT * FROM SESSION_PRIVS;
SELECT LOG_MODE FROM V$DATABASE;
SELECT COUNT(*) FROM V$DATABASE;
SELECT COUNT(*) FROM V$THREAD;
SELECT COUNT(*) FROM V$PARAMETER;
SELECT COUNT(*) FROM V$NLS_PARAMETERS;
SELECT COUNT(*) FROM V$TIMEZONE_NAMES;
SELECT COUNT(*) FROM ALL_INDEXES;
SELECT COUNT(*) FROM ALL_OBJECTS;
SELECT COUNT(*) FROM ALL_USERS;
SELECT COUNT(*) FROM ALL_CATALOG;
SELECT COUNT(*) FROM ALL_CONSTRAINTS;
SELECT COUNT(*) FROM ALL_CONS_COLUMNS;
SELECT COUNT(*) FROM ALL_TAB_COLS;
SELECT COUNT(*) FROM ALL_IND_COLUMNS;
SELECT COUNT(*) FROM ALL_ENCRYPTED_COLUMNS;
SELECT COUNT(*) FROM ALL_LOG_GROUPS;
SELECT COUNT(*) FROM ALL_TAB_PARTITIONS;
SELECT COUNT(*) FROM SYS.DBA_REGISTRY;
SELECT COUNT(*) FROM SYS.OBJ$;
SELECT COUNT(*) FROM DBA_TABLESPACES;
SELECT COUNT(*) FROM DBA_OBJECTS;
SELECT COUNT(*) FROM SYS.ENC$;
SELECT COUNT(*) FROM DBA_PDBS;
SELECT COUNT(*) FROM CDB_TABLES;

ALTER SESSION SET CONTAINER=ORCLPDB1;
SELECT COUNT(*) FROM FASIH.ORDERS;
SELECT COUNT(*) FROM FASIH.PURCHASE;

-- Flashback query privilege
SELECT COUNT(*) FROM FASIH.ORDERS AS OF TIMESTAMP SYSDATE;
SELECT COUNT(*) FROM FASIH.PURCHASE AS OF TIMESTAMP SYSDATE;

-- Added for 19C
SELECT count(*) FROM V$ARCHIVED_LOG;
SELECT count(*) FROM V$LOG;
SELECT count(*) FROM V$LOGFILE;
SELECT count(*) FROM V$INSTANCE;
SELECT SEQUENCE# FROM V$LOG WHERE STATUS = 'CURRENT';
