ALTER SESSION SET CONTAINER=cdb$root;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

-- ONLY FOR PDB
ALTER SESSION SET CONTAINER = ORCLPDB1; 
ALTER TABLE FASIH.ORDERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE FASIH.PURCHASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
